version: '3.7'

services:
  
  client:
    image: client:${TAG}
    build: ./client
    container_name: client
    restart: always
    ports: ['8080:80']
    depends_on: ['server']
    networks: ['transcendence']

  server:
    image: server:${TAG}
    build: ./server
    container_name: server
    restart: always
    depends_on: ['database']
    networks: ['transcendence']
   
  database:
    image: postgres:alpine
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    restart: always
    networks: ['transcendence']

networks:
  transcendence:
    driver: bridge
    name: transcendance
