version: '3.7'

services:
  
  client:
    image: client:42
    container_name: nginx
    restart: always
    ports: ['443:443']
    networks: ['transcendence']

  server:
    image: nodejs:alpine
    container_name: nodejs
    restart: always
    networks: ['transcendence']
  
  database:
    image: postgresql:alpine
    container_name: postgresql
    restart: always
    networks: ['transcendence']

networks:
  transcendence:
    driver: bridge
    name: transcendance