version: '3.7'

services:
  
  client:
    image: client:${TAG}
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    restart: always
    ports: ['3000:3000']
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - server
    networks: ['transcendence']

  server:
    image: server:${TAG}
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    restart: always
    ports: ['4200:4200']
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    depends_on:
      - database
    networks: ['transcendence']
  
  database:
    image: postgres:alpine
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    restart: always
    ports: ['5432:5432']
    networks: ['transcendence']

networks:
  transcendence:
    driver: bridge
    name: transcendance

