export const Events = Object.freeze({
  createChannel: 'createChannel',
  joinChannel: 'joinChannel',
  sendMessage: 'sendMessage',
  updateMessages: 'updateMessages',
  updateChannels: 'updateChannels',
  addUser: 'addUser',
  addUserResponse: 'addUserResponse',
  updateUsers: 'updateUsers',
  userJoined: 'userJoined',
  setId: 'setId',
  setIdResponse: 'setIdResponse',
  joinChannelAnwser: 'joinChannelAnswer',
  updateOneChannel: 'updateOneChannel',
});
