version: '3.8'
services:
  developement-db:
    image: postgres:14
    container_name: postgres_dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - transcendence-network
    restart: on-failure
  redis-session:  
    image: redis:latest
    container_name: redis_dev
    ports:
      - 6379:6379
    restart: on-failure

networks:
  transcendence-network:
