# syntax=docker/dockerfile:1
FROM    node:alpine

# workdir
WORKDIR /app

# copy local files to workdir.
# The folders are then binded through volumes.
COPY	./script/docker-entrypoint.dev.sh 	/usr/local/bin/docker-entrypoint.sh 

# make sure entrypoint can be executed
RUN     chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
