version: '3.8'
services:
  test-db:
    image: postgres:14
    container_name: postgres_test
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - transcendence-network
    restart: on-failure
  test-redis-session:  
    image: redis:latest
    container_name: redis_test
    ports:
      - ${REDIS_PORT}:6379
    restart: on-failure

networks:
  transcendence-network:
