# syntax=docker/dockerfile:1
FROM    node:alpine

# workdir
WORKDIR /app

# copy local files to workdir.
# The folders are then binded through volumes.
COPY    . /app/

# install packages reading package.json
RUN     npm ci 

CMD     ["npm", "run", "start:dev"]
