FROM  alpine:3.16

# get postgres user
ARG   POSTGRES_USER=${POSTGRES_USER}

# install PostgreSQL from package manager
RUN   apk update && apk upgrade && apk add --update --no-cache \
        postgresql \
 &&   rm -f /var/cache/apk/*

# copy entrypoint
COPY  ./scripts/docker-entrypoint.dev.sh ./

COPY  ./conf/dev-mock-data.sql ./
RUN   adduser -D ${POSTGRES_USER}

RUN   mkdir /run/postgresql \
 &&   chown postgres:postgres /run/postgresql

EXPOSE 5432

USER postgres

CMD ["sh"]
