FROM    alpine:3.16

COPY ./conf/dev-mock-data.sql ./

COPY ./scripts/docker-entrypoint.dev.sh ./

ENV POSTGRES_USER=transcendence
ENV POSTGRES_PASSWORD=5euApbMoLVtNgEcKs44e
ENV POSTGRES_DB=transcendence_db

RUN apk update && apk upgrade && apk add --update --no-cache postgresql

RUN adduser -D ${POSTGRES_USER}

RUN mkdir /run/postgresql \
    && chown postgres:postgres /run/postgresql

EXPOSE 5432

USER postgres

# ENTRYPOINT ["./docker-entrypoint.dev.sh"]

CMD ["sh"]