FROM    alpine:3.16

COPY ./conf/dev-mock-data.sql ./

COPY ./scripts/docker-entrypoint.dev.sh ./

RUN apk update && apk upgrade && apk add --update --no-cache postgresql

ARG POSTGRES_USER=${POSTGRES_USER}

RUN adduser -D ${POSTGRES_USER}

RUN mkdir /run/postgresql \
    && chown postgres:postgres /run/postgresql

EXPOSE 5432

USER postgres

CMD ["sh"]