export enum eEvent {
  JoinChannel = 'joinChannel',
  SendMessage = 'sendMessage',
  UpdateMessages = 'updateMessages',
  UpdateOneMessage = 'updateOneMessage',
  UpdateChannels = 'updateChannels',
  UpdateOneChannel = 'updateOneChannel',
  UpdateUsers = 'updateUsers',
  UpdateOneUser = 'updateOneUser',
  JoinChannelResponse = 'joinChannelResponse',
  GetMessages = 'getMessages',
  CreateChannel = 'createChannel',
  InitConnection = 'initConnection',
  UpdateUserOnChannel = 'updateUserOnChannel',
  AddUser = 'addUser',
  AddedToChannel = 'addedToChannel',
  MuteUser = 'muteUser',
  BanUser = 'banUser',
  LeaveChannel = 'leaveChannel',
  LeavingChannel = 'leavingChannel',
}
