export enum eEvent {
  CreateChannel = 'createChannel',
  CreateChannelResponse = 'createChannelResponse',
  JoinChannel = 'joinChannel',
  SendMessage = 'sendMessage',
  UpdateMessages = 'updateMessages',
  UpdateOneMessage = 'updateOneMessage',
  UpdateChannels = 'updateChannels',
  UpdateOneChannel = 'updateOneChannel',
  AddUser = 'addUser',
  AddUserResponse = 'addUserResponse',
  UpdateUsers = 'updateUsers',
  UpdateOneUser = 'updateOneUser',
  UserJoined = 'userJoined',
  SetId = 'setId',
  SetIdResponse = 'setIdResponse',
  JoinChannelResponse = 'joinChannelResponse',
  AddedToRoom = 'addedToRoom',
}
