# syntax=docker/dockerfile:1
FROM    node:alpine

# workdir
WORKDIR /app

# copy local files to workdir.
# The folders are then binded through volumes.
COPY    .   /app

# copy entrypoint
COPY	./script/docker-entrypoint.sh 	/usr/local/bin/

# make sure entrypoint can be executed
RUN     chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
