name: Makefile CI

on:
  push:
    branches: [ "auth_tom_safe" ]
  pull_request:
    branches: [ "auth_tom_safe" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Docker-Compose Up and test
      run: make TESTINT=
