name: Makefile CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Run-integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Docker-Compose Up
      run: make build testing
    - name: Run Integration Tests on the server
      run: make test server int
